
name: Generate Rust Binaries

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact-name: Windows-x86
            os: windows-2022
            rust-flags: --target x86_64-pc-windows-msvc
          - artifact-name: Linux-x86_64
            os: ubuntu-22.04
            rust-flags: --target x86_64-unknown-linux-gnu
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Linux dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -q
        sudo apt-get install -y \
          build-essential \
          curl \
          file \
          libayatana-appindicator3-dev \
          libgtk-3-dev \
          librsvg2-dev \
          libssl-dev \
          libwebkit2gtk-4.0-dev \
          wget
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-gnu
    - name: Set up sccache
      uses: mozilla-actions/sccache-action@v0.0.5
    - run: cargo build ${{ matrix.rust-flags }}
      working-directory: src/main/rust
      env:
        SCCACHE_GHA_ENABLED: "true"
        RUSTC_WRAPPER: "sccache"